//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.10 at 12:08:13 PM BST 
//


package com.acorr.stockPositions.queryResultMessage;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Open_QNAME = new QName("", "Open");
    private final static QName _BookValue_QNAME = new QName("", "BookValue");
    private final static QName _Bid_QNAME = new QName("", "Bid");
    private final static QName _DaysHigh_QNAME = new QName("", "DaysHigh");
    private final static QName _ChangeFromFiftydayMovingAverage_QNAME = new QName("", "ChangeFromFiftydayMovingAverage");
    private final static QName _DaysRange_QNAME = new QName("", "DaysRange");
    private final static QName _ChangePercentChange_QNAME = new QName("", "Change_PercentChange");
    private final static QName _DaysRangeRealtime_QNAME = new QName("", "DaysRangeRealtime");
    private final static QName _LowLimit_QNAME = new QName("", "LowLimit");
    private final static QName _PercentChangeFromTwoHundreddayMovingAverage_QNAME = new QName("", "PercentChangeFromTwoHundreddayMovingAverage");
    private final static QName _ChangeFromTwoHundreddayMovingAverage_QNAME = new QName("", "ChangeFromTwoHundreddayMovingAverage");
    private final static QName _LastTradeDate_QNAME = new QName("", "LastTradeDate");
    private final static QName _TwoHundreddayMovingAverage_QNAME = new QName("", "TwoHundreddayMovingAverage");
    private final static QName _AskRealtime_QNAME = new QName("", "AskRealtime");
    private final static QName _PercentChange_QNAME = new QName("", "PercentChange");
    private final static QName _YearRange_QNAME = new QName("", "YearRange");
    private final static QName _PercentChangeFromFiftydayMovingAverage_QNAME = new QName("", "PercentChangeFromFiftydayMovingAverage");
    private final static QName _Change_QNAME = new QName("", "Change");
    private final static QName _YearHigh_QNAME = new QName("", "YearHigh");
    private final static QName _Symbol_QNAME = new QName("", "Symbol");
    private final static QName _MarketCapitalization_QNAME = new QName("", "MarketCapitalization");
    private final static QName _BidRealtime_QNAME = new QName("", "BidRealtime");
    private final static QName _LastTradePriceOnly_QNAME = new QName("", "LastTradePriceOnly");
    private final static QName _AverageDailyVolume_QNAME = new QName("", "AverageDailyVolume");
    private final static QName _PercentChangeFromYearLow_QNAME = new QName("", "PercentChangeFromYearLow");
    private final static QName _ChangeFromYearHigh_QNAME = new QName("", "ChangeFromYearHigh");
    private final static QName _FiftydayMovingAverage_QNAME = new QName("", "FiftydayMovingAverage");
    private final static QName _PreviousClose_QNAME = new QName("", "PreviousClose");
    private final static QName _StockExchange_QNAME = new QName("", "StockExchange");
    private final static QName _LastTradeTime_QNAME = new QName("", "LastTradeTime");
    private final static QName _DaysLow_QNAME = new QName("", "DaysLow");
    private final static QName _DaysValueChange_QNAME = new QName("", "DaysValueChange");
    private final static QName _HighLimit_QNAME = new QName("", "HighLimit");
    private final static QName _ChangeRealtime_QNAME = new QName("", "ChangeRealtime");
    private final static QName _OneyrTargetPrice_QNAME = new QName("", "OneyrTargetPrice");
    private final static QName _YearLow_QNAME = new QName("", "YearLow");
    private final static QName _PricePaid_QNAME = new QName("", "PricePaid");
    private final static QName _Volume_QNAME = new QName("", "Volume");
    private final static QName _Ask_QNAME = new QName("", "Ask");
    private final static QName _ChangeFromYearLow_QNAME = new QName("", "ChangeFromYearLow");
    private final static QName _PercebtChangeFromYearHigh_QNAME = new QName("", "PercebtChangeFromYearHigh");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _ChangePercentRealtime_QNAME = new QName("", "ChangePercentRealtime");
    private final static QName _DaysValueChangeRealtime_QNAME = new QName("", "DaysValueChangeRealtime");
    private final static QName _EarningsShare_QNAME = new QName("", "EarningsShare");
    private final static QName _PriceBook_QNAME = new QName("", "PriceBook");
    private final static QName _ChangeinPercent_QNAME = new QName("", "ChangeinPercent");
    private final static QName _ShortRatio_QNAME = new QName("", "ShortRatio");
    private final static QName _PriceSales_QNAME = new QName("", "PriceSales");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link Quotes }
     * 
     */
    public Quotes createQuote() {
        return new Quotes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Open")
    public JAXBElement<String> createOpen(String value) {
        return new JAXBElement<String>(_Open_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BookValue")
    public JAXBElement<String> createBookValue(String value) {
        return new JAXBElement<String>(_BookValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bid")
    public JAXBElement<String> createBid(String value) {
        return new JAXBElement<String>(_Bid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DaysHigh")
    public JAXBElement<String> createDaysHigh(String value) {
        return new JAXBElement<String>(_DaysHigh_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangeFromFiftydayMovingAverage")
    public JAXBElement<String> createChangeFromFiftydayMovingAverage(String value) {
        return new JAXBElement<String>(_ChangeFromFiftydayMovingAverage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DaysRange")
    public JAXBElement<String> createDaysRange(String value) {
        return new JAXBElement<String>(_DaysRange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Change_PercentChange")
    public JAXBElement<String> createChangePercentChange(String value) {
        return new JAXBElement<String>(_ChangePercentChange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DaysRangeRealtime")
    public JAXBElement<String> createDaysRangeRealtime(String value) {
        return new JAXBElement<String>(_DaysRangeRealtime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LowLimit")
    public JAXBElement<String> createLowLimit(String value) {
        return new JAXBElement<String>(_LowLimit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PercentChangeFromTwoHundreddayMovingAverage")
    public JAXBElement<String> createPercentChangeFromTwoHundreddayMovingAverage(String value) {
        return new JAXBElement<String>(_PercentChangeFromTwoHundreddayMovingAverage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangeFromTwoHundreddayMovingAverage")
    public JAXBElement<String> createChangeFromTwoHundreddayMovingAverage(String value) {
        return new JAXBElement<String>(_ChangeFromTwoHundreddayMovingAverage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastTradeDate")
    public JAXBElement<String> createLastTradeDate(String value) {
        return new JAXBElement<String>(_LastTradeDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TwoHundreddayMovingAverage")
    public JAXBElement<String> createTwoHundreddayMovingAverage(String value) {
        return new JAXBElement<String>(_TwoHundreddayMovingAverage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AskRealtime")
    public JAXBElement<String> createAskRealtime(String value) {
        return new JAXBElement<String>(_AskRealtime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PercentChange")
    public JAXBElement<String> createPercentChange(String value) {
        return new JAXBElement<String>(_PercentChange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YearRange")
    public JAXBElement<String> createYearRange(String value) {
        return new JAXBElement<String>(_YearRange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PercentChangeFromFiftydayMovingAverage")
    public JAXBElement<String> createPercentChangeFromFiftydayMovingAverage(String value) {
        return new JAXBElement<String>(_PercentChangeFromFiftydayMovingAverage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Change")
    public JAXBElement<String> createChange(String value) {
        return new JAXBElement<String>(_Change_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YearHigh")
    public JAXBElement<String> createYearHigh(String value) {
        return new JAXBElement<String>(_YearHigh_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Symbol")
    public JAXBElement<String> createSymbol(String value) {
        return new JAXBElement<String>(_Symbol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MarketCapitalization")
    public JAXBElement<String> createMarketCapitalization(String value) {
        return new JAXBElement<String>(_MarketCapitalization_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BidRealtime")
    public JAXBElement<String> createBidRealtime(String value) {
        return new JAXBElement<String>(_BidRealtime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastTradePriceOnly")
    public JAXBElement<String> createLastTradePriceOnly(String value) {
        return new JAXBElement<String>(_LastTradePriceOnly_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AverageDailyVolume")
    public JAXBElement<String> createAverageDailyVolume(String value) {
        return new JAXBElement<String>(_AverageDailyVolume_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PercentChangeFromYearLow")
    public JAXBElement<String> createPercentChangeFromYearLow(String value) {
        return new JAXBElement<String>(_PercentChangeFromYearLow_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangeFromYearHigh")
    public JAXBElement<BigDecimal> createChangeFromYearHigh(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ChangeFromYearHigh_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FiftydayMovingAverage")
    public JAXBElement<String> createFiftydayMovingAverage(String value) {
        return new JAXBElement<String>(_FiftydayMovingAverage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PreviousClose")
    public JAXBElement<String> createPreviousClose(String value) {
        return new JAXBElement<String>(_PreviousClose_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StockExchange")
    public JAXBElement<String> createStockExchange(String value) {
        return new JAXBElement<String>(_StockExchange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastTradeTime")
    public JAXBElement<String> createLastTradeTime(String value) {
        return new JAXBElement<String>(_LastTradeTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DaysLow")
    public JAXBElement<String> createDaysLow(String value) {
        return new JAXBElement<String>(_DaysLow_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DaysValueChange")
    public JAXBElement<String> createDaysValueChange(String value) {
        return new JAXBElement<String>(_DaysValueChange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HighLimit")
    public JAXBElement<String> createHighLimit(String value) {
        return new JAXBElement<String>(_HighLimit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangeRealtime")
    public JAXBElement<String> createChangeRealtime(String value) {
        return new JAXBElement<String>(_ChangeRealtime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OneyrTargetPrice")
    public JAXBElement<String> createOneyrTargetPrice(String value) {
        return new JAXBElement<String>(_OneyrTargetPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YearLow")
    public JAXBElement<String> createYearLow(String value) {
        return new JAXBElement<String>(_YearLow_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PricePaid")
    public JAXBElement<String> createPricePaid(String value) {
        return new JAXBElement<String>(_PricePaid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Volume")
    public JAXBElement<String> createVolume(String value) {
        return new JAXBElement<String>(_Volume_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Ask")
    public JAXBElement<String> createAsk(String value) {
        return new JAXBElement<String>(_Ask_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangeFromYearLow")
    public JAXBElement<String> createChangeFromYearLow(String value) {
        return new JAXBElement<String>(_ChangeFromYearLow_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PercebtChangeFromYearHigh")
    public JAXBElement<String> createPercebtChangeFromYearHigh(String value) {
        return new JAXBElement<String>(_PercebtChangeFromYearHigh_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangePercentRealtime")
    public JAXBElement<String> createChangePercentRealtime(String value) {
        return new JAXBElement<String>(_ChangePercentRealtime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DaysValueChangeRealtime")
    public JAXBElement<String> createDaysValueChangeRealtime(String value) {
        return new JAXBElement<String>(_DaysValueChangeRealtime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EarningsShare")
    public JAXBElement<String> createEarningsShare(String value) {
        return new JAXBElement<String>(_EarningsShare_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PriceBook")
    public JAXBElement<String> createPriceBook(String value) {
        return new JAXBElement<String>(_PriceBook_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangeinPercent")
    public JAXBElement<String> createChangeinPercent(String value) {
        return new JAXBElement<String>(_ChangeinPercent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShortRatio")
    public JAXBElement<String> createShortRatio(String value) {
        return new JAXBElement<String>(_ShortRatio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PriceSales")
    public JAXBElement<String> createPriceSales(String value) {
        return new JAXBElement<String>(_PriceSales_QNAME, String.class, null, value);
    }

}
